### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/TracPendingTicketPlugin#1]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to fine trac-hacks plugins, including yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. I'll be writing a blog post soon with more information and will follow-up here with a link to that post.

Kind regards,
- Ryan

**Comment by csnover** [comment]
Where’s the org, is it literally @trac-hacks? That one has no publicised users and doesn’t look new/active so it’s not clear. I would be happy to transfer my few Trac plugins somewhere if it makes good sense to do so.

**Comment by rjollos** [comment]
Yeah, the org is @trac-hacks. Explicitly it can be found here: https://github.com/orgs/trac-hacks. I'll send you an invite.

**Comment by rjollos** [comment]
You should receive two invites to join teams associated with the trac-hacks organization. One team gives you the general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts) and transfer the repository. The second will give you Admin access for a group that your repository will be associated with. After you transfer the repository I'll remove you from the first team, but you'll continue to be an Admin for your repository by virtue of being a member of the second team.

**Comment by rjollos** [comment]
Still interested? I've been working with the jQuery infra team to bring up the new Trac sites and I need to modify TracTicketGraph to support the new database API.

**Comment by rjollos** [comment]
> That one has no publicised users and doesn’t look new/active so it’s not clear.

Btw, fixed the issue of users not being publicized. We currently have 39 members, which you can see after accepting the invite. Only 10 of the members have chosen to make themselves publicly visible to non-members of the org.

**Comment by csnover** [comment]
There are 4 other outstanding repos, TracAnnouncer, TracSimpleTicketPlugin, TracNginxCacheSupport, and TracExposeAttachmentPerms. Which of these should be transferred?

**Comment by csnover** [comment]
I sent over TracTicketGraph and TracPendingTicketPlugin. There are 4 other repos, TracAnnouncer, TracSimpleTicketPlugin, TracNginxCacheSupport, and TracExposeAttachmentPerms. Which of these should be transferred?

**Comment by rjollos** [comment]
TracNginxCacheSupport and TracExposeAttachmentPerms would be good to transfer. Thanks for the fast reply!

**Comment by rjollos** [comment]
Thanks again!
